blank_issues_enabled: false

contact_links:
  - name: GitHub Community Support
    url: https://github.com/yoyoyojoe/press-play/discussions
    about: Please ask and answer questions here.
  - name: Press-Play Security Bug Bounty (N/A)
    url: https://github.com/yoyoyojoe/press-play/issues
    about: Please report security vulnerabilities for Press-Play as an Issue (either feature request or improve content will work) or as a new discussion in Discussions.
  - name: GitHub Security Bug Bounty (outside of Press-Play repo)
    url: https://bounty.github.com/
    about: Please report security vulnerabilities for GitHub here.