name: Reject Wild Issues
on: [issues, pull_request]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Autoclose issues that did not follow issue template
      uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-close-message: "@${issue.user.login} this issue was automatically closed because it did not follow the issue template"
        issue-pattern: ".*I agree to follow this project's Contributing Guidelines and Code of Conduct.*"
        # markdown syntax for hyperlinks were not needed
        close-issue-label: wontfix # not yet supported
        # A sequence was not expected (i.e. [ "wontfix" ] won't work)
        close-issue-reason: not_planned # not yet supported